# Generated by Django 5.0.3 on 2024-03-25 14:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_bid', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_volume', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=17)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=4, max_digits=7)),
                ('is_Bid', models.BooleanField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_limit', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('limit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange.limit')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('size_filled', models.DecimalField(decimal_places=4, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_matches', to='exchange.order')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_matches', to='exchange.order')),
            ],
        ),
        migrations.AddField(
            model_name='limit',
            name='orderbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='exchange.orderbook'),
        ),
    ]
