# Generated by Django 5.0.3 on 2024-03-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_order_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='limit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='exchange.limit'),
        ),
    ]
