# Generated by Django 5.0.3 on 2024-03-26 20:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_order_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size_to_trade',
            field=models.DecimalField(decimal_places=4, default=Decimal('555'), max_digits=7),
        ),
    ]
