# Generated by Django 5.0.3 on 2024-03-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_order_size_to_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderbook',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
