# Generated by Django 5.0.3 on 2024-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_limit_deleted_at_match_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='size_to_trade',
            new_name='size_remained',
        ),
    ]
