# Generated by Django 5.0.3 on 2024-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Filled', 'Filled'), ('Processing', 'Processing'), ('Active_Not_Filled', 'Active Not Filled'), ('Active_Partially_Filled', 'Active Partially Filled'), ('Rejected', 'Rejected'), ('Cancelled_Not_Filled', 'Cancelled Not Filled'), ('Cancelled_Partially_Filled', 'Cancelled Partially Filled')], max_length=50),
        ),
    ]
