# Generated by Django 5.0.3 on 2024-03-27 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderBook',
            field=models.ForeignKey(default='e37d01df-98d4-4fb5-a57e-377dff7919be', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange.orderbook'),
            preserve_default=False,
        ),
    ]
