# Generated by Django 5.0.3 on 2024-03-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_order_orderbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='currency_1',
            field=models.CharField(default='ETH', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderbook',
            name='currency_2',
            field=models.CharField(default='USD', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderbook',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
