# Generated by Django 5.0.3 on 2024-03-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_orderbook_currency_1_orderbook_currency_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderBook',
            new_name='orderbook',
        ),
    ]
