# Generated by Django 5.0.3 on 2024-04-01 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_rename_orderbook_order_orderbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETHAccounts',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('public_key', models.CharField(max_length=100, unique=True)),
                ('is_taken', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
