# Generated by Django 5.0.3 on 2024-04-01 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_ethaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencyType',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_deposit', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.ethaccounts')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.cryptocurrencytype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
