# Generated by Django 4.2.11 on 2024-04-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_rename_crypto_address_usertransaction_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='to_address',
            field=models.ForeignKey(default='30df2c50-2072-47ff-bdfb-a14a8c5c2621', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recieved_transactions', to='exchange.ethaccounts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='from_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_transactions', to='exchange.ethaccounts'),
        ),
    ]
