# Generated by Django 4.2.11 on 2024-04-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_usertransaction_to_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethaccounts',
            name='is_taken',
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='from_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_transactions', to='exchange.ethaccounts'),
        ),
    ]
