# Generated by Django 4.2.11 on 2024-04-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_remove_ethaccounts_is_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='to_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recieved_transactions', to='exchange.ethaccounts'),
        ),
    ]
