# Generated by Django 4.2.11 on 2024-04-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0020_alter_usertransaction_to_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='match_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='exchange.match'),
        ),
    ]
