# Generated by Django 4.2.11 on 2024-04-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_usertransaction_match_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='currency_1_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderbooks_c1', to='exchange.cryptocurrencytype'),
        ),
        migrations.AddField(
            model_name='orderbook',
            name='currency_2_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderbooks_c2', to='exchange.cryptocurrencytype'),
        ),
    ]
