# Generated by Django 4.2.11 on 2024-04-03 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0022_orderbook_currency_1_fk_orderbook_currency_2_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='currency_1',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='currency_2',
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='currency_1_FK',
            field=models.ForeignKey(default='c3a409c4-09d8-4305-97cc-4416ecb71582', on_delete=django.db.models.deletion.CASCADE, related_name='orderbooks_c1', to='exchange.cryptocurrencytype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='currency_2_FK',
            field=models.ForeignKey(default='21d24663-69db-42e5-84f5-45c64ea4bac7', on_delete=django.db.models.deletion.CASCADE, related_name='orderbooks_c2', to='exchange.cryptocurrencytype'),
            preserve_default=False,
        ),
    ]
