# Generated by Django 4.2.11 on 2024-04-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0023_remove_orderbook_currency_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='currency_1_FK',
            new_name='currency_1',
        ),
    ]
