# Generated by Django 4.2.11 on 2024-04-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0024_rename_currency_1_fk_orderbook_currency_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='currency_2_FK',
            new_name='currency_2',
        ),
    ]
