# Generated by Django 4.2.11 on 2024-04-04 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0026_rename_user_usertransaction_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
