# Generated by Django 4.2.11 on 2024-04-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0028_rename_usertransaction_userexternaltransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexternaltransaction',
            name='to_user',
        ),
    ]
