# Generated by Django 4.2.11 on 2024-04-04 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0030_rename_from_user_userexternaltransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexternaltransaction',
            name='user',
            field=models.ForeignKey(default='ea7fa00896d146f38448f09931224389', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
