# Generated by Django 4.2.11 on 2024-04-05 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0031_alter_userexternaltransaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexternaltransaction',
            name='match_transaction',
        ),
        migrations.AlterField(
            model_name='userexternaltransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InternalTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.cryptocurrencytype')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_from', to=settings.AUTH_USER_MODEL)),
                ('match_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='exchange.match')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
