# Generated by Django 4.2.11 on 2024-04-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0032_remove_userexternaltransaction_match_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='size_remained',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
    ]
